blank_issues_enabled: false
contact_links:
    - name: Help
      url: https://github.com/Paraliyzedevo/osu-Radio/discussions/categories/q-a
      about: osu! not working or performing as you'd expect? Not sure it's a bug? Check the Q&A section!
    - name: Suggestions or feature request
      url: https://github.com/Paraliyzedevo/osu-Radio/discussions/categories/ideas
      about: Got something you think should change or be added? Search for or start a new discussion!
    - name: More places to get help
      url: https://discord.gg/E7xYNZpcQX
      about: If you can't seem to get into contact with Paraliyzed_evo or Thunderbirdo, please try to get support in the discord server.
