/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119898-ge6fb8f373e-20250616"
#endif /* AVUTIL_FFVERSION_H */
