name: osu!Radio

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/Library/Caches/pip
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y \
              libxcb-xkb1 \
              libxcb-image0 \
              libxcb-cursor0 \
              libxcb-render-util0 \
              libxcb-shape0 \
              libxcb-icccm4 \
              libxcb-keysyms1 \
              libxkbcommon-x11-0 \
              libpulse0 \
              xvfb
          
            echo "DISPLAY=:99" >> $GITHUB_ENV
            nohup Xvfb :99 -screen 0 1024x768x16 > /dev/null 2>&1 &
          fi
        shell: bash

      - name: Cache ffmpeg_bin
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: osuRadio/ffmpeg_bin
          key: ${{ runner.os }}-ffmpeg_bin-v1

      - name: Install ffmpeg_bin
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          pip install gdown
          gdown https://drive.google.com/uc?id=1lwGVfmVmpHLaUZ6geXXpFFnv7eUAj0gz -O ffmpeg_bin.zip
          unzip ffmpeg_bin.zip -d osuRadio/ffmpeg_bin

      - name: Cache macOS icon
        id: cache-macos-icon
        if: matrix.os == 'macos-latest'
        uses: actions/cache@v4
        with:
          path: osuRadio/Osu!RadioIcon.icns
          key: macos-icon-${{ hashFiles('osuRadio/Osu!RadioIcon.png') }}

      - name: Convert .png to .icns (macOS only)
        if: matrix.os == 'macos-latest' && steps.cache-macos-icon.outputs.cache-hit != 'true'
        run: |
          brew install imagemagick
          cd "osuRadio"
          ICON_NAME="Osu!RadioIcon"
          ICONSET="${ICON_NAME}.iconset"
          mkdir -p "$ICONSET"
          magick "$ICON_NAME.png" "$ICONSET/icon_1024x1024.png"
          sips -z 16 16     "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_16x16.png"
          sips -z 32 32     "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_16x16@2x.png"
          sips -z 32 32     "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_32x32.png"
          sips -z 64 64     "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_32x32@2x.png"
          sips -z 128 128   "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_128x128.png"
          sips -z 256 256   "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_128x128@2x.png"
          sips -z 256 256   "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_256x256.png"
          sips -z 512 512   "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_256x256@2x.png"
          sips -z 512 512   "$ICONSET/icon_1024x1024.png" --out "$ICONSET/icon_512x512.png"
          cp "$ICONSET/icon_1024x1024.png" "$ICONSET/icon_512x512@2x.png"
          iconutil -c icns "$ICONSET" -o "${ICON_NAME}.icns"
          rm -r "$ICONSET"

      - name: Build updater (Windows and Linux)
        if: matrix.os != 'macos-latest'
        run: |
          pyinstaller updater.py --onefile

      - name: Build app (Windows)
        if: matrix.os == 'windows-latest'
        run: pyinstaller Osu!Radio.spec --clean

      - name: Build app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: pyinstaller Osu!Radio-linux.spec --clean

      - name: Build app (macOS)
        if: matrix.os == 'macos-latest'
        run: pyinstaller Osu!Radio-macos.spec --clean

      - name: Install create-dmg (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install create-dmg

      - name: Create .dmg installer (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cp -r "osuRadio/Background Video" "dist/osu!Radio.app/Contents/Resources/"
          cp -r "osuRadio/ffmpeg_bin" "dist/osu!Radio.app/Contents/Resources/"
          cp -r "osuRadio/img" "dist/osu!Radio.app/Contents/Resources/"
          create-dmg \
            --volname "osu!Radio Installer" \
            --volicon "dist/osu!Radio.app/Contents/Resources/Osu!RadioIcon.icns" \
            --window-pos 200 120 \
            --window-size 854 480 \
            --icon-size 100 \
            --app-drop-link 450 185 \
            osu!Radio.dmg \
            dist/osu!Radio.app

      - name: Create .pkg installer (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          pkgbuild \
            --root dist/osu!Radio.app \
            --identifier com.paraliyzedevo.osuradio \
            --version 1.9.0 \
            --install-location /Applications \
            dist/osu!Radio.pkg

      - name: Package output (Windows)
        if: matrix.os == 'windows-latest'
        run: 7z a osu!Radio-windows.zip dist/osu!Radio/*

      - name: Package output (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p 'osu!Radio-linux'
          cp -r 'dist/osu!Radio' 'osu!Radio-linux/'
          cp -r 'osuRadio/Background Video' 'osu!Radio-linux/'
          cp -r 'osuRadio/ffmpeg_bin' 'osu!Radio-linux/'
          cp -r 'osuRadio/img' 'osu!Radio-linux/'
          cp 'dist/updater' 'osu!Radio-linux'
          cp 'osuRadio/Osu!RadioIcon.png' 'osu!Radio-linux/'
          tar -czf 'osu!Radio.tar.gz' -C 'osu!Radio-linux' .

      - name: Copy macOS installers for upload
        if: matrix.os == 'macos-latest'
        run: |
          cp "dist/osu!Radio.pkg" "osu!Radio.pkg"

      - name: Upload build artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: osu!Radio-windows
          path: osu!Radio-windows.zip

      - name: Upload build artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: osu!Radio-linux
          path: osu!Radio.tar.gz

      - name: Upload build artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: osu!Radio-macos
          path: |
            osu!Radio.pkg
            osu!Radio.dmg

      - name: Upload Release Asset (Windows)
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          files: osu!Radio-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (Linux)
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          files: osu!Radio.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (macOS)
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          files: |
            osu!Radio.pkg
            osu!Radio.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}